apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.smfName }}
  labels:
    vnf-name: {{ .Values.vnf_name }}
    vf-module-name: {{ .Values.config.smfName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      vnf-name: {{ .Values.vnf_name }}
      vf-module-name: {{ .Values.config.smfName }}
  template:
    metadata:
      labels:
        vnf-name: {{ .Values.vnf_name }}
        vf-module-name: {{ .Values.config.smfName }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/smf-conf
      volumes:
        - name: config-volume
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: {{ .Values.config.smfName }}-configmap
            items:
              - key: supportedNssai
                path: supportedNssai.json
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          envFrom:
          - configMapRef:
              name: {{ .Values.config.smfName }}-configmap
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      volumes:
        - name: config-volume
          configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: {{ .Values.config.smfName }}-configmap
          items:
            - key: supportedNssai
                path: supportedNssai.json
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}


