apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firewall.name" .}}-configmap
data:
  demo_artifacts_version: {{ .Values.demoArtifactsVersion }}
  vfw_private_ip_0: {{ .Values.vfwPrivateIp0 }}
  vsn_private_ip_0: {{ .Values.vsnPrivateIp0 }}
  protected_net_cidr: {{ .Values.protectedNetCidr }}
  dcae_collector_ip: {{ .Values.dcaeCollectorIp }}
  dcae_collector_port: {{ .Values.dcaCollectorPort }}
  protected_net_gw: {{ .Values.protectedNetGw }}
  protected_private_net_cidr: {{ .Values.protectedPrivateNetCidr }}
