apiVersion: v1
appVersion: "1.0"
description: "A sample horovod application which runs the MNIST application using Tensorflow as backend"
name: sample-horovod-app-keras-mnist-advanced
version: 0.1.0 
