apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectd-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: collectd-operator
  template:
    metadata:
      labels:
        name: collectd-operator
    spec:
      serviceAccountName: collectd-operator
      containers:
        - name: collectd-operator
          # Replace this with the built image name
          image: dcr.cluster.local:31976/collectd-operator:latest
          command:
          - collectd-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "collectd-operator"
