

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

operator:
  image:
    repository: banzaicloud/istio-operator
    tag: 0.2.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

istioVersion: 1.2

## Prometheus Metrics
prometheusMetrics:
  enabled: false
# Enable or disable the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
  authProxy:
    enabled: false

## Role Based Access
## Ref: https://kubernetes.io/docs/admin/authorization/rbac/
##
rbac:
  enabled: true

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}
tolerations: []
affinity: {}
