apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: {{ .Release.Name }}-{{ .Values.etcdCluster.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "m3db.name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
     etcd.database.coreos.com/scope: clusterwide
spec:
  size: {{ .Values.etcdCluster.size }}
  version: "{{ .Values.etcdCluster.version }}"
  pod:
{{ toYaml .Values.etcdCluster.pod | indent 4 }}
  {{- if .Values.etcdCluster.enableTLS }}
  TLS:
{{ toYaml .Values.etcdCluster.tls | indent 4 }}
  {{- end }}
