apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gloo
  name: gloo
  namespace: {{ .Release.Namespace }}
spec:
{{ if .Values.gloo.deployment.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.gloo.deployment.externalTrafficPolicy }}
{{- end }}
  ports:
  - name: grpc
    port: {{ .Values.gloo.deployment.xdsPort }}
    protocol: TCP
  selector:
    gloo: gloo
