{{/*
# Copyright 2019 Intel Corporation, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
*/}}

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        collector: collectd
        release: {{ .Release.Name }}
    spec:
      hostNetwork: true
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          volumeMounts:
          - name: {{ template "fullname" . }}-config
            mountPath: /opt/collectd/etc
          - name: proc
            mountPath: /mnt/proc
            readOnly: true
          - name: root
            mountPath: /hostfs
            readOnly: true
          - name: etc
            mountPath: /mnt/etc
            readOnly: true
          - name: run
            mountPath: /var/run/docker.sock
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
      - name: {{ template "fullname" . }}-config
        configMap:
          name: {{ template "fullname" . }}-config
          items:
          - key: node-collectd.conf
            path: collectd.conf
      - name: proc
        hostPath:
          path: /proc
      - name: root
        hostPath:
          path: /
      - name: etc
        hostPath:
          path: /etc
      - name: run
        hostPath:
          path: /var/run/docker.sock
