$num_compute_nodes = 2

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--natnet1', '192.168.240.0/24']
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize "post-boot",["controlvm", :id, "setlinkstate1", "on"]
  end

  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
  config.vm.synced_folder "..", "/demo"

  config.vm.define "control" do |config|
    config.vm.hostname = "control"
    config.vm.network "private_network", ip: "192.168.0.10"
    config.vm.network "private_network", ip: "192.168.1.10"
    config.vm.provision "shell", path: "setup_control.sh", privileged: false
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 8192]
      vb.customize ["modifyvm", :id, "--cpus", 8]
    end
  end

  (1 .. $num_compute_nodes).each do |n|
    config.vm.define vm_name = "compute-#{n}" do |config|
      config.vm.hostname = vm_name
      config.vm.network "private_network", ip: "192.168.0.#{n+20}"
      config.vm.network "private_network", ip: "192.168.1.#{n+20}"
      config.vm.provision "shell", path: "setup_compute.sh", privileged: false
      config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--memory", 40960 ]
        v.customize ["modifyvm", :id, "--cpus", 8]
        file_to_disk1 = "large_disk_file.#{n}.vdi1"
        v.customize ['createhd', '--filename', file_to_disk1, '--size', 1000 * 1024]
        v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk1 ]
        file_to_disk2 = "large_disk_file.#{n}.vdi2"
        v.customize ['createhd', '--filename', file_to_disk2, '--size', 1000 * 1024]
        v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', file_to_disk2 ]
      end
    end
  end

  config.vm.define "onap" do |config|
    config.vm.hostname = "onap"
    config.vm.network "private_network", ip: "192.168.0.2"
    config.vm.network "private_network", ip: "192.168.1.2"
    config.vm.provision "shell", path: "create_onap.sh", privileged: false
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 4]
    end
  end
end
