apiVersion: skaffold/v1beta6
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: .
      image: hdfs-writer
  local:
    useBuildkit: false
    useDockerCLI: false
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
  - name: cloudbuild
    build:
      googleCloudBuild: {}
