crds:
  create: true
discovery:
  deployment:
    image:
      pullPolicy: Always
      repository: quay.io/solo-io/discovery
      tag: 0.13.18
    replicas: 1
    stats: false
gateway:
  deployment:
    image:
      pullPolicy: Always
      repository: quay.io/solo-io/gateway
      tag: ""
    replicas: 1
    stats: false
  enabled: false
gatewayProxies:
  gateway-proxy:
    configMap:
      data: null
    deployment:
      httpPort: "8080"
      httpsPort: "8443"
      image:
        pullPolicy: Always
        repository: quay.io/solo-io/gloo-envoy-wrapper
        tag: ""
      replicas: 1
      stats: false
    service:
      httpPort: "80"
      httpsPort: "443"
      type: LoadBalancer
gloo:
  deployment:
    image:
      pullPolicy: Always
      repository: quay.io/solo-io/gloo
      tag: 0.13.18
    replicas: 1
    stats: false
    xdsPort: "9977"
ingress:
  deployment:
    image:
      pullPolicy: Always
      repository: quay.io/solo-io/ingress
      tag: 0.13.18
    replicas: 1
    stats: false
  enabled: false
namespace:
  create: false
rbac:
  create: true
settings:
  integrations:
    knative:
      enabled: true
      proxy:
        httpPort: "80"
        httpsPort: "443"
        image:
          pullPolicy: Always
          repository: quay.io/solo-io/gloo-envoy-wrapper
          tag: 0.13.18
        replicas: 1
        stats: false
  writeNamespace: gloo-system
