crds:
  create: true
discovery:
  deployment:
    image:
      pullPolicy: Always
      repository: quay.io/solo-io/discovery
      tag: 0.13.18
    replicas: 1
    stats: false
gateway:
  deployment:
    image:
      pullPolicy: Always
      repository: quay.io/solo-io/gateway
      tag: 0.13.18
    replicas: 1
    stats: false
  enabled: true
gatewayProxies:
  gateway-proxy:
    configMap:
      data: null
    deployment:
      httpPort: "8080"
      httpsPort: "8443"
      image:
        pullPolicy: Always
        repository: quay.io/solo-io/gloo-envoy-wrapper
        tag: 0.13.18
      replicas: 1
      stats: false
    service:
      httpPort: "80"
      httpsPort: "443"
      type: LoadBalancer
gloo:
  deployment:
    image:
      pullPolicy: Always
      repository: quay.io/solo-io/gloo
      tag: 0.13.18
    replicas: 1
    stats: false
    xdsPort: "9977"
ingress:
  enabled: false
namespace:
  create: false
rbac:
  create: true
settings:
  integrations:
    knative:
      enabled: false
  writeNamespace: gloo-system
