# This Service manifest defines:
# - a load balancer for pods matching label "app: go-prom-kafka-writer"
# - exposing the application to the public Internet (type:LoadBalancer)
# - routes port 80 of the load balancer to the port 8686 of the Pods.
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: v1
kind: Service
metadata:
  name: prom-kafka-writer
  labels:
    app: prom-kafka-writer
spec:
  type: NodePort
  selector:
    app: prom-kafka-writer
  ports:
  - name: http
    port: 80
    targetPort: 8686
    nodePort: 30086
