# Static Defaults
replicaCount: 1
image:
  repository: virtlet.cloud/ubuntu/16.04
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 4Gi

# Names
vnf_name: test-vnf
vfw_name_0: test-vnf-vfw
int_private1_net_id: unprotected-net
int_private2_net_id: protected-net
onap_private_net_id: onap-private-net
net_attachment_definition: vfw-net-attach
# OWN Addresses
vfw_int_private1_ip_0: 192.168.10.3
vfw_int_private2_ip_0: 192.168.20.2
vfw_onap_private_ip_0: 10.10.100.3
# Env variables
int_private2_net_cidr: 192.168.20.0/24
vsn_int_private2_ip_0: 192.168.20.3
dcae_collector_port: 8080
dcae_collector_ip: 10.0.4.1 #Placeholder
demo_artifacts_version: 1.5.0

# Tests
Tests:
  enabled: "yes"
  ping_count: 4
