{{- if .Values.enabled }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collectdglobals.onap.org
  labels:
    app: {{ template "collectd-operator.name" . }}
    chart: {{ template "collectd-operator.chart" . }}
    component: collectdglobals.onap.org-crd
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: onap.org
  names:
    kind: CollectdGlobal
    listKind: CollectdGlobalList
    plural: collectdglobals
    singular: collectdglobal
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            configMap:
              type: string
            globalOptions:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - globalOptions
          type: object
        status:
          properties:
            collectdAgents:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html
                CollectdAgents are the collectd pods in the Daemonset Status can be
                one of "", Created, Deleting, Applied, Deprecated'
              items:
                type: string
              type: array
            status:
              type: string
          required:
          - status
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
{{- end }}