{{- if .Values.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: collectd-operator
  labels:
    app: {{ template "collectd-operator.name" . }}
    chart: {{ template "collectd-operator.chart" . }}
    component: clusterrolebinding
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: collectd-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: collectd-operator
  apiGroup: rbac.authorization.k8s.io
{{- end }}