spec:
  remoteRead:
  - url: "http://m3coordinator-m3db.m3db-operator.svc.cluster.local:7201/api/v1/prom/remote/read"
    readRecent: true
  remoteWrite:
  - url: "http://m3coordinator-m3db.m3db-operator.svc.cluster.local:7201/api/v1/prom/remote/write"
    writeRelabelConfigs:
      - targetLabel: metrics_storage
        replacement: m3db_remote
  - url: "http://m3coordinator-m3db-cluster.edge1.svc.cluster.local:7201/api/v1/prom/remote/write"
    writeRelabelConfigs:
      - targetLabel: metrics_storage_day2
        replacement: m3db_remote_day2
