apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.kafka.strimzi.io
  labels:
    app: '{{ template "strimzi.name" . }}'
    chart: '{{ template "strimzi.chart" . }}'
    component: kafkatopics.kafka.strimzi.io-crd
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: kafka.strimzi.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: KafkaTopic
    listKind: KafkaTopicList
    singular: kafkatopic
    plural: kafkatopics
    shortNames:
    - kt
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            partitions:
              type: integer
              minimum: 1
            replicas:
              type: integer
              minimum: 1
              maximum: 32767
            config:
              type: object
            topicName:
              type: string
          required:
          - partitions
          - replicas
