apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ include "tf-serving.fullname" . }}
    labels:
       app: {{ include "tf-serving.name" . }}
       chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
       release: {{ .Release.Name }}
       heritage: {{ .Release.Service | quote }}
