// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/onap/v1alpha1.KafkaConfig":                    schema_pkg_apis_onap_v1alpha1_KafkaConfig(ref),
		"./pkg/apis/onap/v1alpha1.PrometheusRemoteEndpoint":       schema_pkg_apis_onap_v1alpha1_PrometheusRemoteEndpoint(ref),
		"./pkg/apis/onap/v1alpha1.PrometheusRemoteEndpointSpec":   schema_pkg_apis_onap_v1alpha1_PrometheusRemoteEndpointSpec(ref),
		"./pkg/apis/onap/v1alpha1.PrometheusRemoteEndpointStatus": schema_pkg_apis_onap_v1alpha1_PrometheusRemoteEndpointStatus(ref),
		"./pkg/apis/onap/v1alpha1.RemoteFilterAction":             schema_pkg_apis_onap_v1alpha1_RemoteFilterAction(ref),
		"./pkg/apis/onap/v1alpha1.RemoteWriteEndpoint":            schema_pkg_apis_onap_v1alpha1_RemoteWriteEndpoint(ref),
		"./pkg/apis/onap/v1alpha1.Selector":                       schema_pkg_apis_onap_v1alpha1_Selector(ref),
	}
}

func schema_pkg_apis_onap_v1alpha1_KafkaConfig(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "KafkaConfig defines config for kafka broker",
				Properties: map[string]spec.Schema{
					"brokerURL": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"group": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"topic": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"brokerURL", "group", "topic"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_onap_v1alpha1_PrometheusRemoteEndpoint(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PrometheusRemoteEndpoint is the Schema for the prometheusremoteendpoints API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/onap/v1alpha1.PrometheusRemoteEndpointSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/onap/v1alpha1.PrometheusRemoteEndpointStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/onap/v1alpha1.PrometheusRemoteEndpointSpec", "./pkg/apis/onap/v1alpha1.PrometheusRemoteEndpointStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_onap_v1alpha1_PrometheusRemoteEndpointSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PrometheusRemoteEndpointSpec defines the desired state of PrometheusRemoteEndpoint",
				Properties: map[string]spec.Schema{
					"remoteWrite": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("./pkg/apis/onap/v1alpha1.RemoteWriteEndpoint"),
									},
								},
							},
						},
					},
				},
				Required: []string{"remoteWrite"},
			},
		},
		Dependencies: []string{
			"./pkg/apis/onap/v1alpha1.RemoteWriteEndpoint"},
	}
}

func schema_pkg_apis_onap_v1alpha1_PrometheusRemoteEndpointStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "PrometheusRemoteEndpointStatus defines the observed state of PrometheusRemoteEndpoint",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_onap_v1alpha1_RemoteFilterAction(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RemoteFilterAction defines the actions to be taken before writing to the remote systems",
				Properties: map[string]spec.Schema{
					"action": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"regex": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"sourceLabels": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"targetLabel": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"replacement": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"action", "regex", "sourceLabels", "targetLabel", "replacement"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_onap_v1alpha1_RemoteWriteEndpoint(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RemoteWriteEndpoint defines the endpoints and configs of the remote systems",
				Properties: map[string]spec.Schema{
					"url": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"type": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"writeRelabelConfigs": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("./pkg/apis/onap/v1alpha1.RemoteFilterAction"),
									},
								},
							},
						},
					},
					"filterSelector": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/onap/v1alpha1.Selector"),
						},
					},
					"kafkaConfig": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/onap/v1alpha1.KafkaConfig"),
						},
					},
				},
				Required: []string{"url", "type", "writeRelabelConfigs", "filterSelector", "kafkaConfig"},
			},
		},
		Dependencies: []string{
			"./pkg/apis/onap/v1alpha1.KafkaConfig", "./pkg/apis/onap/v1alpha1.RemoteFilterAction", "./pkg/apis/onap/v1alpha1.Selector"},
	}
}

func schema_pkg_apis_onap_v1alpha1_Selector(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Selector defines selectors for selecting appropriate systems",
				Properties: map[string]spec.Schema{
					"remote": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"remote"},
			},
		},
		Dependencies: []string{},
	}
}
