apiVersion: v1
kind: Service
metadata:
  name: {{ include "prom-kafka-writer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "prom-kafka-writer.name" . }}
    helm.sh/chart: {{ include "prom-kafka-writer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
    {{- if ( and (eq .Values.service.type "NodePort" ) (not (empty .Values.service.nodePort)) ) }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "prom-kafka-writer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "prom-kafka-writer.name" . }}
