apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-remote-config-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prometheus-remote-config-operator
  template:
    metadata:
      labels:
        name: prometheus-remote-config-operator
    spec:
      serviceAccountName: prometheus-remote-config-operator
      containers:
        - name: prometheus-remote-config-operator
          # Replace this with the built image name
          image: dcr.cluster.local:32644/prometheus-remote-config-operator:latest
          command:
          - prometheus-remote-config-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "prometheus-remote-config-operator"