##########################################################################
#
#==================LICENSE_START==========================================
#
#
# Copyright 2017 AT&T Intellectual Property. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#==================LICENSE_END============================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.
#
##########################################################################

heat_template_version: 2013-05-23

description: Heat template to deploy vCPE vBRG Emulator (vBRGEMU) for ONAP

#######################################################################
#                                                                     #
# PARAMETERS 							                                            #
#                                                                     #
#     0_port should get IP address from DHCP discover through vBNG    #
#     DCAE is not monitoring the BRGEMULATOR                          #
#######################################################################

parameters:
  vcpe_image_name:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
  vcpe_flavor_name:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
  public_net_id:
    type: string
    label: Public network name or ID
    description: Public network that enables remote connection to VNF
  vbrgemu_bng_private_net_id:
    type: string
    label: vBNG private network name or ID
    description: Private network that connects vBRGEMU to vBNG
  vbrgemu_bng_private_net_cidr:
    type: string
    label: vBNG IN private network CIDR
    description: The CIDR of the input side of vBNG private network
  vbrgemu_private_net_id:
    type: string
    label: vBRGEMU Home private network name or ID
    description: Private network that connects vBRGEMU to local devices
  vbrgemu_private_net_cidr:
    type: string
    label: vBRGEMU Home private network CIDR
    description: The CIDR of the input side of vBRGEMU Home private network
  vbrgemu_private_ip_0:
    type: string
    label: vGW private IP address
    description: Private IP address towards the BRGEMU-BNG network
  vbrgemu_private_ip_1:
    type: string
    label: vGW private IP address
    description: Private IP address towards the BRGEMU private network
  vbrgemu_name_0:
    type: string
    label: vGW  name
    description: Name of the vGW
  vnf_id:
    type: string
    label: VNF ID
    description: The VNF ID is provided by ONAP
  vf_module_id:
    type: string
    label: vCPE module ID
    description: The vCPE Module ID is provided by ONAP
  key_name:
    type: string
    label: Key pair name
    description: Public/Private key pair name
  pub_key:
    type: string
    label: Public key
    description: Public key to be installed on the compute instance
  repo_url_blob:
    type: string
    label: Repository URL
    description: URL of the repository that hosts the demo packages
  repo_url_artifacts:
    type: string
    label: Repository URL
    description: URL of the repository that hosts the demo packages
  install_script_version:
    type: string
    label: Installation script version number
    description: Version number of the scripts that install the vFW demo app
  demo_artifacts_version:
    type: string
    label: Artifacts version used in demo vnfs
    description: Artifacts (jar, tar.gz) version used in demo vnfs
  cloud_env:
    type: string
    label: Cloud environment
    description: Cloud environment (e.g., openstack, rackspace)
  vpp_source_repo_url:
    type: string
    label: VPP Source Git Repo
    description: URL for VPP source codes
  vpp_source_repo_branch:
    type: string
    label: VPP Source Git Branch
    description: Git Branch for the VPP source codes
  hc2vpp_source_repo_url:
    type: string
    label: Honeycomb Source Git Repo
    description: URL for Honeycomb source codes
  hc2vpp_source_repo_branch:
    type: string
    label: Honeycomb Source Git Branch
    description: Git Branch for the Honeycomb source codes
  vpp_patch_url:
    type: string
    label: VPP Patch URL
    description: URL for VPP patch for vBRG Emulator
  sdnc_ip:
    type: string
    label: SDNC ip address
    description: SDNC ip address uesd to set NAT

#############
#           #
# RESOURCES #
#           #
#############

resources:

  random-str:
    type: OS::Heat::RandomString
    properties:
      length: 4

  my_keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: base_rand
          params:
            base: { get_param: key_name }
            rand: { get_resource: random-str }
      public_key: { get_param: pub_key }
      save_private_key: false

  vbrgemu_private_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: vbrgemu_private_net_id }

  vbrgemu_private_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: vbrgemu_private_net_id }
      network_id: { get_resource: vbrgemu_private_network }
      cidr: { get_param: vbrgemu_private_net_cidr }

  # Virtual BRG Emulator Instantiation
  # 0_port should get IP address from DHCP discover through vBNG once the VNF is running
  vbrgemu_private_0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: vbrgemu_bng_private_net_id }
      fixed_ips: [{"subnet": { get_param: vbrgemu_bng_private_net_id }, "ip_address": { get_param: vbrgemu_private_ip_0 }}]

  vbrgemu_private_1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: vbrgemu_private_network }
      fixed_ips: [{"subnet": { get_resource: vbrgemu_private_subnet }, "ip_address": { get_param: vbrgemu_private_ip_1 }}]

  vbrgemu_0:
    type: OS::Nova::Server
    properties:
      image: { get_param: vcpe_image_name }
      flavor: { get_param: vcpe_flavor_name }
      name: { get_param: vbrgemu_name_0 }
      key_name: { get_resource: my_keypair }
      networks:
        - network: { get_param: public_net_id }
        - port: { get_resource: vbrgemu_private_0_port }
        - port: { get_resource: vbrgemu_private_1_port }
      metadata: {vnf_id: { get_param: vnf_id }, vf_module_id: { get_param: vf_module_id }}
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __brgemu_net_ipaddr__: { get_param: vbrgemu_private_ip_1 }
            __brgemu_cidr__: { get_param: vbrgemu_private_net_cidr }
            __brgemu_bng_private_net_cidr__: { get_param: vbrgemu_bng_private_net_cidr }
            __repo_url_blob__ : { get_param: repo_url_blob }
            __repo_url_artifacts__ : { get_param: repo_url_artifacts }
            __demo_artifacts_version__ : { get_param: demo_artifacts_version }
            __install_script_version__ : { get_param: install_script_version }
            __cloud_env__ : { get_param: cloud_env }
            __vpp_source_repo_url__ : { get_param: vpp_source_repo_url }
            __vpp_source_repo_branch__ : { get_param: vpp_source_repo_branch }
            __hc2vpp_source_repo_url__ : { get_param: hc2vpp_source_repo_url }
            __hc2vpp_source_repo_branch__ : { get_param: hc2vpp_source_repo_branch }
            __vpp_patch_url__ : { get_param: vpp_patch_url }
	    __sdnc_ip__ : { get param: sdnc_ip }
          template: |
            #!/bin/bash

            # Create configuration files
            mkdir /opt/config
            echo "__brgemu_net_ipaddr__" > /opt/config/brgemu_net_ipaddr.txt
            echo "__brgemu_cidr__" > /opt/config/brgemu_net_cidr.txt
            echo "__brgemu_bng_private_net_cidr__" > /opt/config/brgemu_bng_private_net_cidr.txt
            echo "__repo_url_blob__" > /opt/config/repo_url_blob.txt
            echo "__repo_url_artifacts__" > /opt/config/repo_url_artifacts.txt
            echo "__demo_artifacts_version__" > /opt/config/demo_artifacts_version.txt
            echo "__install_script_version__" > /opt/config/install_script_version.txt
            echo "__cloud_env__" > /opt/config/cloud_env.txt
            echo "__vpp_source_repo_url__" > /opt/config/vpp_source_repo_url.txt
            echo "__vpp_source_repo_branch__" > /opt/config/vpp_source_repo_branch.txt
            echo "__hc2vpp_source_repo_url__" > /opt/config/hc2vpp_source_repo_url.txt
            echo "__hc2vpp_source_repo_branch__" > /opt/config/hc2vpp_source_repo_branch.txt
            echo "__vpp_patch_url__" > /opt/config/vpp_patch_url.txt
	    echo "__sdnc_ip__" > /opt/config/ip.txt

            # Download and run install script
            curl -k __repo_url_blob__/org.onap.demo/vnfs/vcpe/__install_script_version__/v_brgemu_install.sh -o /opt/v_brgemu_install.sh
            cd /opt
            chmod +x v_brgemu_install.sh
            ./v_brgemu_install.sh
