##########################################################################
#
#==================LICENSE_START==========================================
# 
#
# Copyright 2017 AT&T Intellectual Property. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#        http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#==================LICENSE_END============================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.
#
##########################################################################

heat_template_version: 2013-05-23

description: Heat template to deploy vCPE Infrastructue emlements (vAAA, vDHCP, vDNS_DHCP) for ONAP

##############
#            #
# PARAMETERS #
#            #
##############

parameters:
  vcpe_image_name:
    type: string
    label: Image name or ID
    description: Image to be used for compute instance
  vcpe_flavor_name:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used
  public_net_id:
    type: string
    label: Public network name or ID
    description: Public network that enables remote connection to VNF
  cpe_signal_net_id:
    type: string
    label: vAAA private network name or ID
    description: Private network that connects vAAA with vDNSs
  onap_private_net_id:
    type: string
    label: ONAP management network name or ID
    description: Private network that connects ONAP components and the VNF
  cpe_public_net_id:
    type: string
    label: vCPE Public network (emulates internet) name or ID
    description: Private network that connects vGW to emulated internet
  onap_private_subnet_id:
    type: string
    label: ONAP management sub-network name or ID
    description: Private sub-network that connects ONAP components and the VNF
  cpe_signal_net_cidr:
    type: string
    label: vAAA private network CIDR
    description: The CIDR of the vAAA private network
  onap_private_net_cidr:
    type: string
    label: ONAP private network CIDR
    description: The CIDR of the protected private network
  cpe_public_net_cidr:
    type: string
    label: vCPE public network CIDR
    description: The CIDR of the vCPE public 
  vaaa_private_ip_0:
    type: string
    label: vAAA private IP address towards the private network
    description: Private IP address that is assigned to the vAAA to communicate with the vCPE components 
  vaaa_private_ip_1:
    type: string
    label: vAAA private IP address towards the ONAP management network
    description: Private IP address that is assigned to the vAAA to communicate with ONAP components
  vdns_private_ip_0:
    type: string
    label: vDNS private IP address towards the private network
    description: Private IP address that is assigned to the vDNS to communicate with the vCPE components
  vdns_private_ip_1:
    type: string
    label: vDNS private IP address towards the ONAP management network
    description: Private IP address that is assigned to the vDNS to communicate with ONAP components
  vdhcp_private_ip_0:
    type: string
    label: vDHCP  private IP address towards the private network
    description: Private IP address that is assigned to the vDHCP to communicate with the vCPE components
  vdhcp_private_ip_1:
    type: string
    label: vDNS private IP address towards the ONAP management network
    description: Private IP address that is assigned to the vDHCP to communicate with ONAP components
  vaaa_name_0:
    type: string
    label: vAAA name
    description: Name of the vAAA
  vdns_name_0:
    type: string
    label: vDNS name
    description: Name of the vDNS
  vdhcp_name_0:
    type: string
    label: vDHCP name
    description: Name of the vDHCP
  vnf_id:
    type: string
    label: VNF ID
    description: The VNF ID is provided by ONAP
  vf_module_id:
    type: string
    label: vFirewall module ID
    description: The vAAA Module ID is provided by ONAP
  dcae_collector_ip:
    type: string
    label: DCAE collector IP address
    description: IP address of the DCAE collector
  dcae_collector_port:
    type: string
    label: DCAE collector port
    description: Port of the DCAE collector
  key_name:
    type: string
    label: Key pair name
    description: Public/Private key pair name
  pub_key:
    type: string
    label: Public key
    description: Public key to be installed on the compute instance
  repo_url_blob:
    type: string
    label: Repository URL
    description: URL of the repository that hosts the demo packages
  repo_url_artifacts:
    type: string
    label: Repository URL
    description: URL of the repository that hosts the demo packages
  install_script_version:
    type: string
    label: Installation script version number
    description: Version number of the scripts that install the vFW demo app
  demo_artifacts_version:
    type: string
    label: Artifacts version used in demo vnfs
    description: Artifacts (jar, tar.gz) version used in demo vnfs
  cloud_env:
    type: string
    label: Cloud environment
    description: Cloud environment (e.g., openstack, rackspace)

#############
#           #
# RESOURCES #
#           #
#############

resources:

  random-str:
    type: OS::Heat::RandomString
    properties:
      length: 4

  my_keypair:
    type: OS::Nova::KeyPair
    properties:
      name:
        str_replace:
          template: base_rand
          params:
            base: { get_param: key_name }
            rand: { get_resource: random-str }
      public_key: { get_param: pub_key }
      save_private_key: false

  cpe_signal_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: cpe_signal_net_id }
  cpe_signal_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: cpe_signal_net_id }
      network_id: { get_resource: cpe_signal_network }
      cidr: { get_param: cpe_signal_net_cidr }

  cpe_public_network:
    type: OS::Neutron::Net
    properties:
      name: { get_param: cpe_public_net_id }
  cpe_public_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: { get_param: cpe_public_net_id }
      network_id: { get_resource: cpe_public_network }
      cidr: { get_param: cpe_public_net_cidr }


  # Virtual Load Balancer Instantiation
  vaaa_private_0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: cpe_signal_network }
      fixed_ips: [{"subnet": { get_resource: cpe_signal_subnet }, "ip_address": { get_param: vaaa_private_ip_0 }}]

  vaaa_private_1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: onap_private_net_id }
      fixed_ips: [{"subnet": { get_param: onap_private_subnet_id }, "ip_address": { get_param: vaaa_private_ip_1 }}]

  vaaa_0:
    type: OS::Nova::Server
    properties:
      image: { get_param: vcpe_image_name }
      flavor: { get_param: vcpe_flavor_name }
      name: { get_param: vaaa_name_0 }
      key_name: { get_resource: my_keypair }
      networks:
        - network: { get_param: public_net_id }
        - port: { get_resource: vaaa_private_0_port }
        - port: { get_resource: vaaa_private_1_port }
      metadata: {vnf_id: { get_param: vnf_id }, vf_module_id: { get_param: vf_module_id }}
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __dcae_collector_ip__: { get_param: dcae_collector_ip }
            __dcae_collector_port__: { get_param: dcae_collector_port }
            __local_private_ipaddr__: { get_param: vaaa_private_ip_0 }
            __repo_url_blob__ : { get_param: repo_url_blob }
            __repo_url_artifacts__ : { get_param: repo_url_artifacts }
            __demo_artifacts_version__ : { get_param: demo_artifacts_version }
            __install_script_version__ : { get_param: install_script_version }
            __cloud_env__ : { get_param: cloud_env }
          template: |
            #!/bin/bash

            # Create configuration files
            mkdir /opt/config
            echo "__dcae_collector_ip__" > /opt/config/dcae_collector_ip.txt
            echo "__dcae_collector_port__" > /opt/config/dcae_collector_port.txt
            echo "__local_private_ipaddr__" > /opt/config/local_private_ipaddr.txt
            echo "__repo_url_blob__" > /opt/config/repo_url_blob.txt
            echo "__repo_url_artifacts__" > /opt/config/repo_url_artifacts.txt
            echo "__demo_artifacts_version__" > /opt/config/demo_artifacts_version.txt
            echo "__install_script_version__" > /opt/config/install_script_version.txt
            echo "__cloud_env__" > /opt/config/cloud_env.txt

            # Download and run install script
            curl -k __repo_url_blob__/org.onap.demo/vnfs/vaaa/__install_script_version__/v_aaa_install.sh -o /opt/v_aaa_install.sh
            cd /opt
            chmod +x v_aaa_install.sh
            ./v_aaa_install.sh


  # Virtual DNS Instantiation
  vdns_private_0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: cpe_public_network }
      fixed_ips: [{"subnet": { get_resource: cpe_public_subnet }, "ip_address": { get_param: vdns_private_ip_0 }}]

  vdns_private_1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: onap_private_net_id }
      fixed_ips: [{"subnet": { get_param: onap_private_subnet_id }, "ip_address": { get_param: vdns_private_ip_1 }}]

  vdns_0:
    type: OS::Nova::Server
    properties:
      image: { get_param: vcpe_image_name }
      flavor: { get_param: vcpe_flavor_name }
      name: { get_param: vdns_name_0 }
      key_name: { get_resource: my_keypair }
      networks:
        - network: { get_param: public_net_id }
        - port: { get_resource: vdns_private_0_port }
        - port: { get_resource: vdns_private_1_port }
      metadata: {vnf_id: { get_param: vnf_id }, vf_module_id: { get_param: vf_module_id }}
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __lb_oam_int__ : { get_param: vaaa_private_ip_1 }
            __lb_private_ipaddr__: { get_param: vaaa_private_ip_0 }
            __local_private_ipaddr__: { get_param: vdns_private_ip_0 }
            __repo_url_blob__ : { get_param: repo_url_blob }
            __repo_url_artifacts__ : { get_param: repo_url_artifacts }
            __demo_artifacts_version__ : { get_param: demo_artifacts_version }
            __install_script_version__ : { get_param: install_script_version }
            __cloud_env__ : { get_param: cloud_env }
          template: |
            #!/bin/bash

            # Create configuration files
            mkdir /opt/config
            echo "__lb_oam_int__" > /opt/config/lb_oam_int.txt
            echo "__lb_private_ipaddr__" > /opt/config/lb_private_ipaddr.txt
            echo "__local_private_ipaddr__" > /opt/config/local_private_ipaddr.txt
            echo "__repo_url_blob__" > /opt/config/repo_url_blob.txt
            echo "__repo_url_artifacts__" > /opt/config/repo_url_artifacts.txt
            echo "__demo_artifacts_version__" > /opt/config/demo_artifacts_version.txt
            echo "__install_script_version__" > /opt/config/install_script_version.txt
            echo "__cloud_env__" > /opt/config/cloud_env.txt

            # Download and run install script
            curl -k __repo_url_blob__/org.onap.demo/vnfs/vdns/__install_script_version__/v_dns_install.sh -o /opt/v_dns_install.sh
            cd /opt
            chmod +x v_dns_install.sh
            ./v_dns_install.sh


  # Virtual DHCP Instantiation
  vdhcp_private_0_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: cpe_signal_network }
      fixed_ips: [{"subnet": { get_resource: cpe_signal_subnet }, "ip_address": { get_param: vdhcp_private_ip_0 }}]

  vdhcp_private_1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: onap_private_net_id }
      fixed_ips: [{"subnet": { get_param: onap_private_subnet_id }, "ip_address": { get_param: vdhcp_private_ip_1 }}]

  vdhcp_0:
    type: OS::Nova::Server
    properties:
      image: { get_param: vcpe_image_name }
      flavor: { get_param: vcpe_flavor_name }
      name: { get_param: vdhcp_name_0 }
      key_name: { get_resource: my_keypair }
      networks:
        - network: { get_param: public_net_id }
        - port: { get_resource: vdhcp_private_0_port }
        - port: { get_resource: vdhcp_private_1_port }
      metadata: {vnf_id: { get_param: vnf_id }, vf_module_id: { get_param: vf_module_id }}
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            __lb_oam_int__ : { get_param: vaaa_private_ip_1 }
            __lb_private_ipaddr__: { get_param: vaaa_private_ip_0 }
            __local_private_ipaddr__: { get_param: vdhcp_private_ip_0 }
            __repo_url_blob__ : { get_param: repo_url_blob }
            __repo_url_artifacts__ : { get_param: repo_url_artifacts }
            __demo_artifacts_version__ : { get_param: demo_artifacts_version }
            __install_script_version__ : { get_param: install_script_version }
            __cloud_env__ : { get_param: cloud_env }
          template: |
            #!/bin/bash

            # Create configuration files
            mkdir /opt/config
            echo "__lb_oam_int__" > /opt/config/lb_oam_int.txt
            echo "__lb_private_ipaddr__" > /opt/config/lb_private_ipaddr.txt
            echo "__local_private_ipaddr__" > /opt/config/local_private_ipaddr.txt
            echo "__repo_url_blob__" > /opt/config/repo_url_blob.txt
            echo "__repo_url_artifacts__" > /opt/config/repo_url_artifacts.txt
            echo "__demo_artifacts_version__" > /opt/config/demo_artifacts_version.txt
            echo "__install_script_version__" > /opt/config/install_script_version.txt
            echo "__cloud_env__" > /opt/config/cloud_env.txt

            # Download and run install script
            curl -k __repo_url_blob__/org.onap.demo/vnfs/vdhcp/__install_script_version__/v_dhcp_install.sh -o /opt/v_dhcp_install.sh
            cd /opt
            chmod +x v_dhcp_install.sh
            ./v_dhcp_install.sh
