// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdGlobal) DeepCopyInto(out *CollectdGlobal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdGlobal.
func (in *CollectdGlobal) DeepCopy() *CollectdGlobal {
	if in == nil {
		return nil
	}
	out := new(CollectdGlobal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectdGlobal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdGlobalList) DeepCopyInto(out *CollectdGlobalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CollectdGlobal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdGlobalList.
func (in *CollectdGlobalList) DeepCopy() *CollectdGlobalList {
	if in == nil {
		return nil
	}
	out := new(CollectdGlobalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectdGlobalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdGlobalSpec) DeepCopyInto(out *CollectdGlobalSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdGlobalSpec.
func (in *CollectdGlobalSpec) DeepCopy() *CollectdGlobalSpec {
	if in == nil {
		return nil
	}
	out := new(CollectdGlobalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdGlobalStatus) DeepCopyInto(out *CollectdGlobalStatus) {
	*out = *in
	if in.CollectdAgents != nil {
		in, out := &in.CollectdAgents, &out.CollectdAgents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdGlobalStatus.
func (in *CollectdGlobalStatus) DeepCopy() *CollectdGlobalStatus {
	if in == nil {
		return nil
	}
	out := new(CollectdGlobalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdPlugin) DeepCopyInto(out *CollectdPlugin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdPlugin.
func (in *CollectdPlugin) DeepCopy() *CollectdPlugin {
	if in == nil {
		return nil
	}
	out := new(CollectdPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectdPlugin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdPluginList) DeepCopyInto(out *CollectdPluginList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CollectdPlugin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdPluginList.
func (in *CollectdPluginList) DeepCopy() *CollectdPluginList {
	if in == nil {
		return nil
	}
	out := new(CollectdPluginList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectdPluginList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdPluginSpec) DeepCopyInto(out *CollectdPluginSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdPluginSpec.
func (in *CollectdPluginSpec) DeepCopy() *CollectdPluginSpec {
	if in == nil {
		return nil
	}
	out := new(CollectdPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdPluginStatus) DeepCopyInto(out *CollectdPluginStatus) {
	*out = *in
	if in.CollectdAgents != nil {
		in, out := &in.CollectdAgents, &out.CollectdAgents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdPluginStatus.
func (in *CollectdPluginStatus) DeepCopy() *CollectdPluginStatus {
	if in == nil {
		return nil
	}
	out := new(CollectdPluginStatus)
	in.DeepCopyInto(out)
	return out
}
