CC=gcc

#******************************************************************************
# Standard compiler flags.                                                    *
#******************************************************************************
CPPFLAGS=
CFLAGS=-Wall -g -fPIC

all:     hello_evel_world

hello_evel_world: hello_evel_world.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -o hello_evel_world hello_evel_world.c

